# Generated by Django 4.1.7 on 2023-02-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_filedownload_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='FileDownload',
        ),
    ]
